"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FactionEnum = void 0;
var FactionEnum;
(function (FactionEnum) {
    FactionEnum[FactionEnum["KitCore"] = 1] = "KitCore";
    FactionEnum[FactionEnum["KjasCore"] = 2] = "KjasCore";
    FactionEnum[FactionEnum["CaylionCore"] = 3] = "CaylionCore";
    FactionEnum[FactionEnum["FaderanCore"] = 4] = "FaderanCore";
    FactionEnum[FactionEnum["UnityCore"] = 5] = "UnityCore";
    FactionEnum[FactionEnum["UnityCoreBuffs"] = 6] = "UnityCoreBuffs";
    FactionEnum[FactionEnum["EniEtCore"] = 7] = "EniEtCore";
    FactionEnum[FactionEnum["ImDrilCore"] = 8] = "ImDrilCore";
    FactionEnum[FactionEnum["ZethCore"] = 9] = "ZethCore";
    FactionEnum[FactionEnum["YengiiCore"] = 10] = "YengiiCore";
    FactionEnum[FactionEnum["KitAlt"] = 11] = "KitAlt";
    FactionEnum[FactionEnum["KjasAlt"] = 12] = "KjasAlt";
    FactionEnum[FactionEnum["CaylionAlt"] = 13] = "CaylionAlt";
    FactionEnum[FactionEnum["FaderanAlt"] = 14] = "FaderanAlt";
    FactionEnum[FactionEnum["UnityAlt"] = 15] = "UnityAlt";
    FactionEnum[FactionEnum["EniEtAlt"] = 16] = "EniEtAlt";
    FactionEnum[FactionEnum["ImDrilAlt"] = 17] = "ImDrilAlt";
    FactionEnum[FactionEnum["ZethAlt"] = 18] = "ZethAlt";
    FactionEnum[FactionEnum["YengiiAlt"] = 19] = "YengiiAlt";
    FactionEnum[FactionEnum["KitVorg"] = 20] = "KitVorg";
    FactionEnum[FactionEnum["KjasVorg"] = 21] = "KjasVorg";
    FactionEnum[FactionEnum["CaylionVorg"] = 22] = "CaylionVorg";
    FactionEnum[FactionEnum["FaderanVorg"] = 23] = "FaderanVorg";
    FactionEnum[FactionEnum["UnityVorg"] = 24] = "UnityVorg";
    FactionEnum[FactionEnum["EniEtVorg"] = 25] = "EniEtVorg";
    FactionEnum[FactionEnum["ImDrilVorg"] = 26] = "ImDrilVorg";
    FactionEnum[FactionEnum["ZethVorg"] = 27] = "ZethVorg";
    FactionEnum[FactionEnum["YengiiVorg"] = 28] = "YengiiVorg";
})(FactionEnum || (exports.FactionEnum = FactionEnum = {}));
